config/routes.rb
Rails.application.routes.draw do
  resources :houses
  get 'importer/form'
  post 'importer/upload'
  resources :characters
  root to: 'home#index'
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :house
  has_many :images
  validates :name, :description, presence: true
end
# == Schema Information
#
# Table name: characters
#
#  id                  :integer          not null, primary key
#  name                :string
#  house_id            :integer
#  description         :string
#  biography           :string
#  personality         :string
#  titles              :string
#  status              :string
#  death               :string
#  origin              :string
#  allegiance          :string
#  religion            :string
#  predecessor         :string
#  successor           :string
#  father              :string
#  mother              :string
#  spouse              :string
#  children            :string
#  siblings            :string
#  lovers              :string
#  culture             :string
#  appears_in_season_1 :boolean
#  appears_in_season_2 :boolean
#  appears_in_season_3 :boolean
#  appears_in_season_4 :boolean
#  appears_in_season_5 :boolean
#  appears_in_season_6 :boolean
#  appears_in_season_7 :boolean
#  appears_in_season_8 :boolean
#  appears_in_season_9 :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
    @characters = Character.all.order(:name).page(params[:page]).per(26)
  end

  def show
  end

  def new
    @character = Character.new
  end

  def edit
  end

  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(
        :name,
        :house_id,
        :description,
        :personality,
        :origin,
        :allegiance,
        :religion,
        :culture,
        :titles,
        :status,
        :death,
        :predecessor,
        :successor,
        :father,
        :mother,
        :spouse,
        :children,
        :siblings,
        :lovers,
        :appears_in_season_1,
        :appears_in_season_2,
        :appears_in_season_3,
        :appears_in_season_4,
        :appears_in_season_5,
        :appears_in_season_6,
        :appears_in_season_7,
        :appears_in_season_8,
        :appears_in_season_9)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def format_fields(field, character_field)
    content_tag :div, :class => ["col-md-3", "col-sm-3", "col-lg-3", "col-xs-12"] do
      content_tag(:h2, field.capitalize) +
      content_tag(:p, split_per_character(character_field, ","))
    end if character_field
  end

  def show_character_relationship_fields
    %w(father mother spouse children siblings predecessor successor lovers)
  end

  def show_character_beliefs_fields
    %w(origin culture allegiance religion)
  end
end

app/views/characters/_character.html.erb
<div class="col-md-6 col-lg-6 col-xs-12 list-container">
  <div class="col-md-12 col-lg-3 col-xs-3">
    <% if character.images.first %>
      <%=  image_tag("#{character.images.first.source}", :class => 'img-responsive') %>
    <% else %>
      <%=  image_tag("default.png", :class => 'img-responsive') %>
    <% end %>
  </div>
  <div class="col-md-12 col-lg-9 col-xs-9">
    <h2><%= character.name %>
      <span class="house-name pull-right"><%= character.house.name %></span>
    </h2>
    <% if character.status.present? %>
      <p><em><%= character.status %></em></p>
    <% end %>
    <% if character.death.present? %>
      <p><b>Death:</b> <%= character.death.truncate(40, omission: "...") %></p>
    <% end %>
  </div>
  <%= link_to("", character_path(character) , :class => 'box-show-link') %>
</div>

app/views/characters/_form.html.erb
<%= form_for(character) do |f| %>
  <% if character.errors.any? %>
    <div class="alert alert-warning">
      <h4><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h4>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :house_id %>
    <%= f.select(:house_id, House.all.map {|h| [h.name, h.id] }, {include_blank: 'Select a house'}, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= f.label :biography %>
    <%= f.text_area :biography, :class => 'form-control', rows: "5" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => 'form-control', rows: "5" %>
  </div>

  <div class="form-group">
    <%= f.label :personality %>
    <%= f.text_area :personality, :class => 'form-control', rows: "5" %>
  </div>

  <div class="form-group">
    <%= f.label :origin %>
    <%= f.text_field :origin, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :allegiance %>
    <%= f.text_field :allegiance, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :religion %>
    <%= f.text_field :religion, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :culture %>
    <%= f.text_field :culture, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :titles %>
    <%= f.text_field :titles, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :death %>
    <%= f.text_field :death, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :predecessor %>
    <%= f.text_field :predecessor, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :successor %>
    <%= f.text_field :successor, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :father %>
    <%= f.text_field :father, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :mother %>
    <%= f.text_field :mother, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :spouse %>
    <%= f.text_field :spouse, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :children %>
    <%= f.text_field :children, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :siblings %>
    <%= f.text_field :siblings, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :lovers %>
    <%= f.text_field :lovers, :class => 'form-control' %>
  </div>

  <div class="row">
    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_1 %>
      <%= f.check_box :appears_in_season_1, :class => 'form-control' %>
    </div>

    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_2 %>
      <%= f.check_box :appears_in_season_2, :class => 'form-control' %>
    </div>

    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_3 %>
      <%= f.check_box :appears_in_season_3, :class => 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_4 %>
      <%= f.check_box :appears_in_season_4, :class => 'form-control' %>
    </div>

    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_5 %>
      <%= f.check_box :appears_in_season_5, :class => 'form-control' %>
    </div>

    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_6 %>
      <%= f.check_box :appears_in_season_6, :class => 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_7 %>
      <%= f.check_box :appears_in_season_7, :class => 'form-control' %>
    </div>

    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_8 %>
      <%= f.check_box :appears_in_season_8, :class => 'form-control' %>
    </div>

    <div class="form-group col-md-4 col-lg-4 col-xs-12">
      <%= f.label :appears_in_season_9 %>
      <%= f.check_box :appears_in_season_9, :class => 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/characters/_show_section.html.erb
<% if fields.select { |f| character[f].present? }.size > 0 %>
  <h1><%= title %></h1>
<% end %>
<% fields.select { |f| character[f].present? }.each_slice(4) do |fields| %>
  <div class="row">
    <% fields.each do |f| %>
      <%= format_fields(f, character[f]) %>
    <% end %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show character', @character %>

app/views/characters/index.html.erb
<h1>Characters
<%= link_to 'New Character', new_character_path, :class => 'btn btn-default pull-right' %></h1>

<% @characters.each_slice(2) do |character1, character2| %>
  <div class="row">
    <%= render partial: "character", locals: {character: character1} %>
    <%= render partial: "character", locals: {character: character2} if character2 %>
  </div>
<% end %>

<div class="col-md-12 col-lg-12 col-xs-12 text-center">
  <%= paginate @characters, theme: 'twitter-bootstrap-3' %>
</div>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

app/views/characters/show.html.erb
<div class="col-md-12 col-lg-12 col-xs-12 character">
  <div class="col-lg-12 col-md-12 col-xs-12 character-header">
    <div class="col-md-2 col-lg-2 col-xs-3">
      <% if @character.images.first %>
        <%=  image_tag("#{@character.images.first.source}", :class => 'img-responsive') %>
      <% else %>
        <%=  image_tag("default.png", :class => 'img-responsive') %>
      <% end %>
    </div>
    <div class="col-md-10 col-lg-10 col-xs-9">
      <h2><%= @character.name %></h2>
      <h3>From <%= link_to @character.house.name, house_path(@character.house.id) %></h3>
      <% if @character.titles.present? %>
        <p><b>Titles:</b> <%= @character.titles %></p>
      <% end %>
      <% if @character.status.present? %>
        <p><b>Status:</b> <%= @character.status %></p>
      <% end %>
      <% if @character.death.present? %>
        <p><b>Death:</b> <%= @character.death %></p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h1>General</h1>
    <div class="col-md-5 col-lg-5 col-xs-12">
      <h2>Description</h2>
      <p><%= @character.description %></p>
    </div>
    <div class="col-md-7 col-lg-7 col-xs-12">
      <% if @character.biography.present? %>
        <h2>Biography</h2>
        <p><%= @character.biography %></p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <%= render partial: "show_section", locals: { fields: show_character_relationship_fields,
                                                  character: @character,
                                                  title: "Relationships"} %>
  </div>
  <div class="row">
    <%= render partial: "show_section", locals: { fields: show_character_beliefs_fields,
                                                  character: @character,
                                                  title: "Personal beliefs"} %>
    <% if @character.personality.present? %>
      <h2>Personality</h2>
      <p><%= split_per_character(@character.personality, "\n") %></p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12 col-xs-12">
      <h1>Appeareance in the serie</h1>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <% (1..9).each do |i| %>
            <th class="text-center">
            <%= "Season #{i}" %>
            </th>
            <% end %>
          </thead>
          <tbody>
            <% (1..9).each do |i| %>
            <td>
            <% if @character["appears_in_season_#{i}"] == true %>
            <%=  image_tag('check')%>
            <% else %>
            <%=  image_tag('times')%>
            <% end %>
            </td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <% if @character.images.size > 1 %>
        <h2>Other images</h2>
        <% @character.images[1..-1].each do |image| %>
        <div class="col-md-3 col-lg-3">
        <%= image_tag(image.source, :class => 'img-responsive') %>
        <p class="caption text-center">
          <%= image.caption %>
        </p>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <%= link_to 'Modify character', edit_character_path(@character), :class => 'btn btn-default' %>
    </div>
  </div>
</div>